/* Unit testing for outcomes
(C) 2013-2019 Niall Douglas <http://www.nedproductions.biz/> (6 commits)


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#if defined(__cpp_coroutines)

#include <boost/outcome/coroutine_support.hpp>
#include <boost/outcome/outcome.hpp>
#include <boost/outcome/try.hpp>
#include "quickcpplib/boost/test/unit_test.hpp"

inline BOOST_OUTCOME_V2_NAMESPACE::awaitable<BOOST_OUTCOME_V2_NAMESPACE::result<int>> awaitable_int(int x)
{
  co_return x + 1;
}
inline BOOST_OUTCOME_V2_NAMESPACE::task<BOOST_OUTCOME_V2_NAMESPACE::result<int>> task_int(int x)
{
  co_return x + 1;
}
inline BOOST_OUTCOME_V2_NAMESPACE::awaitable<BOOST_OUTCOME_V2_NAMESPACE::result<int>> awaitable_error()
{
  co_return boost::system::errc::not_enough_memory;
}
inline BOOST_OUTCOME_V2_NAMESPACE::task<BOOST_OUTCOME_V2_NAMESPACE::result<int>> task_error()
{
  co_return boost::system::errc::not_enough_memory;
}
inline BOOST_OUTCOME_V2_NAMESPACE::awaitable<BOOST_OUTCOME_V2_NAMESPACE::result<void>> awaitable_void()
{
  co_return boost::system::errc::not_enough_memory;
}
inline BOOST_OUTCOME_V2_NAMESPACE::task<BOOST_OUTCOME_V2_NAMESPACE::result<void>> task_void()
{
  co_return boost::system::errc::not_enough_memory;
}

template <class U, class... Args> inline BOOST_OUTCOME_V2_NAMESPACE::awaitable<BOOST_OUTCOME_V2_NAMESPACE::result<std::string>> awaitable_coawait(U &&f, Args... args)
{
  BOOST_OUTCOME_CO_TRY(co_await f(args...));
  co_return "hi";
}
template <class U, class... Args> inline BOOST_OUTCOME_V2_NAMESPACE::task<BOOST_OUTCOME_V2_NAMESPACE::result<std::string>> task_coawait(U &&f, Args... args)
{
  BOOST_OUTCOME_CO_TRY(co_await f(args...));
  co_return "hi";
}

#ifndef BOOST_NO_EXCEPTIONS
struct custom_exception_type
{
};
inline BOOST_OUTCOME_V2_NAMESPACE::task<BOOST_OUTCOME_V2_NAMESPACE::result<int, boost::exception_ptr>> result_exception(boost::exception_ptr e)
{
  boost::rethrow_exception(e);
  co_return 5;
}

inline BOOST_OUTCOME_V2_NAMESPACE::task<BOOST_OUTCOME_V2_NAMESPACE::outcome<int>> outcome_exception(boost::exception_ptr e)
{
  boost::rethrow_exception(e);
  co_return 5;
}
#endif

inline BOOST_OUTCOME_V2_NAMESPACE::awaitable<int> awaitable_int2(int x)
{
  co_return x + 1;
}
inline BOOST_OUTCOME_V2_NAMESPACE::task<int> task_int2(int x)
{
  co_return x + 1;
}
inline BOOST_OUTCOME_V2_NAMESPACE::awaitable<void> awaitable_void2()
{
  co_return;
}
inline BOOST_OUTCOME_V2_NAMESPACE::task<void> task_void2()
{
  co_return;
}

BOOST_OUTCOME_AUTO_TEST_CASE(works_result_coroutine, "Tests that results are awaitable and task awaitable")
{
  using namespace BOOST_OUTCOME_V2_NAMESPACE;
  auto awaitable_await = [](auto t) { return t.await_resume(); };
  auto task_await = [](auto t) {
    t.await_suspend({});
    return t.await_resume();
  };

  BOOST_CHECK(awaitable_await(awaitable_int(5)).value() == 6);
  BOOST_CHECK(task_await(task_int(5)).value() == 6);
  BOOST_CHECK(awaitable_await(awaitable_error()).error() == boost::system::errc::not_enough_memory);
  BOOST_CHECK(task_await(task_error()).error() == boost::system::errc::not_enough_memory);
  BOOST_CHECK(awaitable_await(awaitable_void()).error() == boost::system::errc::not_enough_memory);
  BOOST_CHECK(task_await(task_void()).error() == boost::system::errc::not_enough_memory);

  BOOST_CHECK(awaitable_await(awaitable_coawait(awaitable_int, 5)).value() == "hi");
  BOOST_CHECK(task_await(task_coawait(task_int, 5)).value() == "hi");

#ifndef BOOST_NO_EXCEPTIONS
  auto e = boost::copy_exception(custom_exception_type());
  BOOST_CHECK_THROW(task_await(result_exception(e)).value(), custom_exception_type);
  BOOST_CHECK_THROW(task_await(outcome_exception(e)).value(), custom_exception_type);
#endif

  BOOST_CHECK(awaitable_await(awaitable_int2(5)) == 6);
  BOOST_CHECK(task_await(task_int2(5)) == 6);
  awaitable_await(awaitable_void2());
  task_await(task_void2());
}
#else
int main(void)
{
  return 0;
}
#endif
